### ISSUE TITLE
Trust Signing your custom rom with public key

### ISSUE THREAD

**Issue by ol-ti** [Professor-Berni/android_device_sony_suzuran#1]
Hello,
I tried your 17.1 rom from november 2020 on. Stable and snappy as hell, thanks a lot for this masterpiece of work.
I have a quite small issue. Even with the current build, Trust tells me that this build was signed with the public key instead of the private one. Or did I made a mistake?

**Comment by Professor-Berni** [comment]
I **may** sign my build with a private key. But at first I see no benefit and at second I tried it and failed.

**Comment by ol-ti** [comment]
I don't need the signing, I just noticed it because Android advertises the use of Trust on first launch, I tried it and then this message came up. The "benefit" would be "only" that everyone can be sure that the build comes from you.
To speak  **"Trusted. Build and published by Prof. Berni"**. ;-)
