### ISSUE TITLE
Does suzuran currently boot lineage-21.0 and does the corresponding branch of kernel work properly?

### ISSUE THREAD

**Issue by JerryCheng1** [Professor-Berni/android_device_sony_suzuran#2]
I'm going to build 21.0 for SHARP shv33/503sh/dm-01h, so I'm here to know the Z5 device and port the code of MSM8994

**Comment by fpemud** [comment]
I'm going to build Lineage OS for my old Sony Z5C, and I'm also looking for the answer to this question.
Thanks.

**Comment by Professor-Berni** [comment]
The device boots up and runs quite stably.
